const EQUIPMENT_CATEGORY = "equipment"
const WEAPON_CATEGORY = "weapons"
export const productsData = [
    {
        productId: "1",
        quantityInStock: 25,
        category: WEAPON_CATEGORY,
        subCategories: [],
        type: "sword",
        subTypes: [""],
        productName: "Emberfang Blade",
        productDescription: "Finely crafted longsword imbued with the essence of a fire drake.",
        productFullDescription: "The Emberfang Blade is a finely crafted longsword imbued with the essence of a fire drake. Its blade shimmers with a faint, fiery glow, and the hilt is adorned with intricate dragon motifs. This weapon is favored by adventurers seeking to harness the power of flame in their quests. Wielding the Emberfang Blade grants the user a +2 bonus to attack rolls and deals an extra 1d6 fire damage on a successful hit. Ideal for slicing through both enemies and the darkness of the deepest dungeons, this sword is a must-have for any aspiring hero.",
        productDetails: [
            "Enchanted Fire Essence: Infused with the essence of a fire drake, the blade shimmers with a faint, fiery glow.",
            "Attack Bonus: Grants a +2 bonus to attack rolls, enhancing accuracy and effectiveness in combat.",
            "Fire Damage: Deals an additional 1d6 fire damage on a successful hit, burning enemies with each strike.",
            "Exquisite Craftsmanship: Forged with precision and care, the blade boasts intricate dragon motifs on the hilt.",
            "Durable Construction: Made from high-quality materials, ensuring long-lasting durability and reliability in battle.",
            "Balanced Design: Perfectly balanced for smooth, powerful swings, making it ideal for skilled swordsmen.",
            "Heroic Aesthetic: Its striking appearance makes it a symbol of power and prestige among adventurers.",
            "Versatile Use: Effective in various com, bat scenarios, from close-quarters battles to slashing through dense obstacles.",
            "Collector's Item: A highly sought-after weapon, prized for both its combat prowess and its beauty."
        ],
        productPrice: 1200,
        manufacturer: "Dragonfire Forge",
        productImageUrl: "/weapons/dnd-sword-1.jpg"
    },
    {
        productId: "2",
        quantityInStock: 1,
        category: WEAPON_CATEGORY,
        subCategories: [],
        type: "dagger",
        subTypes: [""],
        productName: "Shadowstrike Dagger",
        productDescription: "A sleek and deadly weapon, perfect for rogues and assassins.",
        productFullDescription: "The Shadowstrike Dagger is a sleek and deadly weapon, perfect for rogues and assassins. Crafted from obsidian and enchanted with shadow magic, its blade absorbs light, making it nearly invisible in darkness. The hilt is wrapped in dark leather, providing a comfortable and secure grip. This dagger grants a +1 bonus to attack rolls and deals an additional 1d4 necrotic damage on a successful hit. Silent and swift, the Shadowstrike Dagger is the ultimate tool for those who move unseen and strike without warning.",
        productDetails: ["Enchanted Obsidian Blade: Forged from rare obsidian and imbued with shadow magic, the blade absorbs light and remains nearly invisible in darkness, enhancing stealth.",
            "Enhanced Attack Bonus: Provides a +1 bonus to attack rolls, increasing your chances of landing a successful hit.",
            "Necrotic Damage: Deals an additional 1d4 necrotic damage on a successful hit, sapping the life force of your enemies.",
            "Ergonomic Leather Hilt: Wrapped in dark leather for a comfortable and secure grip, ensuring precise control during combat.",
            "Lightweight Design: Easy to conceal and quick to draw, perfect for rogues, assassins, and those who prefer agility and speed in combat.",
            "Silent Strikes: Designed for silent and swift attacks, ideal for those who need to move unseen and strike without warning.",
            "Exquisite Craftsmanship: Handcrafted at Dragonfire Forge, renowned for its unparalleled quality and attention to detail."
        ],
        productPrice: 750,
        manufacturer: "Dragonfire Forge",
        productImageUrl: "/weapons/dnd-dagger-1.jpg"
    },
    {
        productId: "3",
        quantityInStock: 10,
        category: WEAPON_CATEGORY,
        subCategories: [],
        type: "crossbow",
        subTypes: [""],
        productName: "Stormpiercer Crossbow",
        productDescription: "Perfect for rangers and sharpshooters who seek precision and power.",
        productFullDescription: "The Stormpiercer Crossbow is a masterfully engineered weapon, perfect for rangers and sharpshooters who seek precision and power. Forged with a combination of lightweight mithril and enchanted oak, this crossbow is as durable as it is deadly. The limbs of the bow are etched with runes that crackle with latent lightning magic, giving each bolt a chance to deliver an electrifying shock to the target. The Stormpiercer Crossbow grants a +2 bonus to attack rolls and deals an additional 1d8 lightning damage on a successful hit. Its sleek design and unparalleled accuracy make it the favored choice for those who strike from afar with devastating effectiveness.",
        productDetails: [
            "Lightning-Infused Bolts: Each shot has a chance to deliver an additional 1d8 lightning damage, electrifying targets on impact.",
            "Enhanced Accuracy: Grants a +2 bonus to attack rolls, ensuring precise and deadly strikes from a distance.",
            "Lightweight Construction: Crafted from mithril and enchanted oak, providing durability without compromising maneuverability.",
            "Silent Shooting: Designed to fire arrows almost silently, perfect for stealth operations and surprise attacks.",
            "Runic Enhancements: Etched with ancient runes that channel latent lightning magic, amplifying the weapon's power."
        
        ],
        productPrice: 900,
        manufacturer: "Dragonfire Forge",
        productImageUrl: "/weapons/dnd-crossbow-1.jpg"
    },
    {
        productId: "4",
        quantityInStock: 12,
        category: WEAPON_CATEGORY,
        subCategories: [],
        type: "hand axe",
        subTypes: [""],
        productName: "Frostbite Hand Axe",
        productDescription: "Perfect for warriors who prefer close combat with a touch of elemental power.",
        productFullDescription: "The Frostbite Hand Axe is a finely crafted weapon, perfect for warriors who prefer close combat with a touch of elemental power. Forged from enchanted steel and infused with the essence of an ice elemental, the blade of this hand axe gleams with a frosty sheen. Its edge is perpetually cold to the touch, capable of freezing the flesh of those it strikes. The Frostbite Hand Axe grants a +1 bonus to attack rolls and deals an additional 1d6 cold damage on a successful hit. Compact and deadly, this axe is ideal for adventurers who want to combine brute force with the chilling power of ice.",
        productDetails: [
            "Cold-Infused Blade: The blade is perpetually cold to the touch, dealing an additional 1d6 cold damage on a successful hit.",
            "Attack Bonus: Grants a +1 bonus to attack rolls, enhancing the wielder's precision and effectiveness in close combat.",
            "Durable Craftsmanship: Forged from enchanted steel, ensuring the axe remains sharp and reliable through countless battles.",
            "Ergonomic Grip: Features a comfortable, non-slip handle designed for maximum control and ease of use.",
            "Frosty Aesthetic: The blade gleams with a frosty sheen, making it both a visually striking and intimidating weapon."
        ],
        productPrice: 925,
        manufacturer: "Dragonfire Forge",
        productImageUrl: "/weapons/dnd-handaxe-1.jpg",
    },
    {
        productId: "5",
        quantityInStock: 3,
        category: WEAPON_CATEGORY,
        subCategories: [],
        type: "longbow",
        subTypes: [""],
        productName: "Whisperwind Longbow",
        productDescription: "A beautifully crafted weapon, ideal for archers who value precision and grace.",
        productFullDescription: "The Whisperwind Longbow is a beautifully crafted weapon, ideal for archers who value precision and grace. Made from the finest yew wood and reinforced with elven silver, this longbow is both lightweight and incredibly durable. The bowstring hums with an almost inaudible melody, a testament to the ancient enchantments woven into its fibers. The Whisperwind Longbow grants a +2 bonus to attack rolls and allows its wielder to shoot arrows that travel silently, making it perfect for stealthy operations. Each arrow fired from this bow seems to glide effortlessly through the air, striking targets with uncanny accuracy. Elegant and lethal, the Whisperwind Longbow is the preferred choice for those who strike from the shadows.",
        productDetails: [
            "Enhanced Precision: Grants a +2 bonus to attack rolls, ensuring highly accurate shots over long distances.",
            "Silent Arrows: Designed to shoot arrows silently, perfect for stealthy operations and undetected strikes.",
            "Lightweight and Durable: Crafted from fine yew wood and reinforced with elven silver, offering a perfect balance of strength and agility.",
            "Ancient Enchantments: Bowstring hums with latent magic, giving each arrow a smooth and effortless flight."
        ],
        productPrice: 925,
        manufacturer: "Brimstone Steelworks",
        productImageUrl: "/weapons/dnd-longbow-1.jpg",
    },
    {
        productId: "6",
        quantityInStock: 5,
        category: EQUIPMENT_CATEGORY,
        subCategories: [],
        type: "lantern",
        subTypes: [""],
        productName: "Radiant Dawn Lantern",
        productDescription: "Provides a reliable and brilliant light in the darkest of dungeons and the most treacherous wilderness.",
        productFullDescription: "The Radiant Dawn Lantern is an essential item for any adventurer, providing reliable and brilliant light in the darkest of dungeons and the most treacherous wilderness. Crafted with a combination of durable metals and enchanted glass, this lantern ensures long-lasting illumination and resilience against the elements. Perfect for lighting your path and revealing hidden dangers, the Radiant Dawn Lantern is a must-have for every journey.",
        productDetails: [
            "Enchanted Glass: The lantern's glass is enchanted to emit a bright, steady light that never flickers, ensuring constant visibility.",
            "Adjustable Brightness: Features a dial to adjust the intensity of the light, from a soft glow for stealthy movement to a bright beam for full illumination.",
            "Long-Lasting Fuel: Uses a special, long-lasting oil blend that provides up to 24 hours of continuous light on a single fill.",
            "Weatherproof Design: Built to withstand harsh conditions, including rain, wind, and extreme temperatures, ensuring it remains functional in any environment.",
            "Lightweight and Portable: Compact and easy to carry, with a sturdy handle for hanging or holding, making it perfect for adventurers on the move."
        ],
        productPrice: 50,
        manufacturer: "Everbright Essentials",
        productImageUrl: "/equipment/dnd-lantern-1.jpg",
    },
    {
        productId: "7",
        quantityInStock: 5,
        category: EQUIPMENT_CATEGORY,
        subCategories: [],
        type: "lantern",
        subTypes: [""],
        productName: "Twilight Guardian Lantern",
        productDescription: "Designed for adventurers who require dependable light in the darkest and most dangerous places.",
        productFullDescription: "The Twilight Guardian Lantern is a premium illumination device designed for adventurers who require dependable light in the darkest and most dangerous places. Crafted from high-quality materials and imbued with protective enchantments, this lantern not only lights your way but also offers magical protection against the creatures of the night. Ideal for explorers, dungeon delvers, and nighttime scouts, the Twilight Guardian Lantern is your faithful companion in the shadows.",
        productDetails: [
            "Protective Aura: Emits a faint magical aura that repels minor shadow creatures, providing an extra layer of safety.",
            "Dimmable Light: Features adjustable light settings, allowing you to switch from a gentle glow for stealth to a bright beam for exploration.",
            "Extended Burn Time: Utilizes enchanted fuel that provides up to 48 hours of continuous light, reducing the need for frequent refills.",
            "Sturdy Construction: Made from reinforced steel and arcane glass, ensuring durability and resistance to damage.",
            "Water-Resistant: Designed to function reliably in wet conditions, including heavy rain and damp dungeons.",
            "Multi-Mount Options: Equipped with a versatile mounting system, allowing it to be hung, carried, or mounted on a belt or backpack."
        ],
        productPrice: 75,
        manufacturer: "Everbright Essentials",
        productImageUrl: "/equipment/dnd-lantern-2.jpg",
    },
    {
        productId: "8",
        quantityInStock: 2,
        category: EQUIPMENT_CATEGORY,
        subCategories: [],
        type: "lantern",
        subTypes: [""],
        productName: "Moonbeam Lantern",
        productDescription: "Perfect for adventurers who need reliable illumination in a lightweight and portable design.",
        productFullDescription: "The Moonbeam Lantern is a compact and elegant lighting solution, perfect for adventurers who need reliable illumination in a lightweight and portable design. Infused with lunar magic, this lantern casts a soft, soothing light that can reveal hidden details and create a calming ambiance. Ideal for camping, night-time reading, or exploring mystical ruins, the Moonbeam Lantern is both practical and enchanting.",
        productDetails: [
            "Lunar-Infused Light: Emits a gentle, calming glow that enhances visibility without being harsh on the eyes, ideal for both functional and aesthetic use.",
            "Compact and Lightweight: Designed for easy portability, this lantern is small enough to fit in a backpack or be carried by hand without adding significant weight.",
            "Rechargeable: Powered by a rechargeable magic crystal, providing up to 12 hours of light on a single charge, and easily replenished at any arcane energy source.",
        ],
        productPrice: 30,
        manufacturer: "Everbright Essentials",
        productImageUrl: "/equipment/dnd-lantern-3.jpg",
    },
    {
        productId: "9",
        quantityInStock: 1,
        category: EQUIPMENT_CATEGORY,
        subCategories: [],
        type: "lantern",
        subTypes: [""],
        productName: "Emberglow Lantern",
        productDescription: "Perfect for adventurers who need dependable illumination in challenging environments.",
        productFullDescription: "The Emberglow Lantern is a robust and reliable light source, perfect for adventurers who need dependable illumination in challenging environments. Crafted with a focus on durability and ease of use, this lantern provides a warm, steady light that can withstand rough handling and adverse conditions. Ideal for rugged expeditions and extended journeys, the Emberglow Lantern is an essential piece of gear for any serious adventurer.",
        productDetails: [
            "Shock-Resistant Construction: Built to endure drops and impacts, ensuring it remains functional even in the toughest conditions.",
            "Warm Steady Light: Provides a consistent, warm glow that enhances visibility and creates a comfortable atmosphere in camp or on the move.",
            "Fuel-Efficient: Designed to maximize burn time, providing up to 36 hours of light on a single tank of fuel, making it ideal for long trips.",
        ],
        productPrice: 40,
        manufacturer: "Everbright Essentials",
        productImageUrl: "/equipment/dnd-lantern-4.jpg",
    },
    {
        productId: "10",
        quantityInStock: 1,
        category: EQUIPMENT_CATEGORY,
        subCategories: [],
        type: "backpack",
        subTypes: [""],
        productName: "Wanderer's Haven Backpack",
        productDescription: "The ultimate companion for adventurers who need a reliable and spacious bag to carry their gear.",
        productFullDescription: "The Wanderer's Haven Backpack is the ultimate companion for adventurers who need a reliable and spacious bag to carry their gear. Designed with durability and comfort in mind, this backpack features multiple compartments and enhanced carrying capacity, making it perfect for long journeys and challenging expeditions. Whether you're traversing rugged terrain or exploring hidden dungeons, the Wanderer's Haven Backpack ensures your essentials are securely stored and easily accessible.",
        productDetails: [
            "Enhanced Storage Capacity: Multiple compartments and pockets provide ample space for all your gear, including a special padded section for delicate items.",
            "Comfortable Design: Ergonomically designed with adjustable, padded shoulder straps and a breathable back panel to ensure maximum comfort during long treks.",
            "Weather-Resistant Material: Made from durable, weather-resistant fabric that protects your belongings from rain, mud, and other elements.",
            "Reinforced Stitching: Double-stitched seams and reinforced stress points ensure long-lasting durability, even under heavy loads.",
        ],
        productPrice: 65,
        manufacturer: "Pathfinder Provisions",
        productImageUrl: "/equipment/dnd-backpack-1.jpg",
    },
    {
        productId: "11",
        quantityInStock: 0,
        category: EQUIPMENT_CATEGORY,
        subCategories: [],
        type: "backpack",
        subTypes: [""],
        productName: "Explorer's Endurance Pack",
        productDescription: "A high-quality backpack designed for adventurers who demand durability and versatility. ",
        productFullDescription: " The Explorer's Endurance Pack is a high-quality backpack designed for adventurers who demand durability and versatility. With its rugged construction and innovative features, this backpack is ideal for long expeditions, offering ample storage and superior comfort. Whether you're scaling mountains or delving into dungeons, the Explorer's Endurance Pack will keep your gear organized and secure.",
        productDetails: [
            "Expandable Compartments: Features expandable compartments that allow for increased storage capacity, perfect for carrying additional supplies or treasures found during your adventures.",
            "Hydration System Compatible: Includes a dedicated compartment and hose routing for a hydration bladder, ensuring you stay hydrated on the go.",
            "Integrated Tool Loops: Equipped with external loops for easy access to essential tools like ropes, picks, and Secure Fastenings: Sturdy buckles and zippers ensure your gear stays securely packed, even in the roughest conditions.lanterns.",
            "Secure Fastenings: Sturdy buckles and zippers ensure your gear stays securely packed, even in the roughest conditions.",
            "Quick-Access Pockets: Strategically placed pockets allow for easy access to frequently used items like maps, potions, and snacks.",
        ],
        productPrice: 75,
        manufacturer: "Pathfinder Provisions",
        productImageUrl: "/equipment/dnd-backpack-2.jpg",
    },
]