import type { Metadata } from "next";
import { cinzel, roboto } from './fonts/fonts';
import Header from "@/components/header/Header"
import "./globals.css";

export const metadata: Metadata = {
  title: "Adventure Guild - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cinzel.variable} ${roboto.variable}`}>
      <body className="body-background">
      <Header />
        {children}
        </body>
    </html>
  );
}
